enable-module-update = false # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

[TikTok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
